import { Routes } from '@angular/router';
import { SignupComponent } from './shared/components/signup/signup.component';
import { LoginComponent } from './shared/components/login/login.component';
import { HomeComponent } from './shared/components/home/home.component';
import { StudentListComponent } from './features/student/components/student-list/student-list.component';
import { StudentDetailComponent } from './features/student/components/student-detail/student-detail.component';
import { BookListComponent } from './features/book/components/book-list/book-list.component';
import { ProfileComponent } from './shared/components/profile/profile.component';
import { BookDetailComponent } from './features/book/components/book-detail/book-detail.component';
import { BookFormComponent } from './features/book/components/book-form/book-form.component';
import { MyBorrowBooksComponent } from './features/book/components/my-borrow-books/my-borrow-books.component';
import { FineComponent } from './features/fine/components/fine/fine.component';
import { LogoutComponent } from './shared/components/logout/logout.component';
import { UserComponent } from './features/user/components/user/user.component';
import { UserDetailsComponent } from './features/user/components/user-details/user-details.component';
import { StudentBorrowHistoryComponent } from './features/student/components/student-borrow-history/student-borrow-history.component';
import { AllBooksBorrowedComponent } from './features/book/components/all-books-borrowed/all-books-borrowed.component';

export const routes: Routes = [
    { path: "", component: HomeComponent },
    { path: "home", component: HomeComponent },
    { path: "signup", component: SignupComponent },
    { path: "login", component: LoginComponent },
    { path: "student", component: StudentListComponent },
    { path: "studentDetail", component: StudentDetailComponent },
    { path: "updateStudent", component: SignupComponent },
    { path: "book", component: BookListComponent },
    { path: 'profile', component: ProfileComponent },
    { path: 'bookDetails', component: BookDetailComponent },
    { path: 'addBook', component: BookFormComponent },
    { path: 'updateBook', component: BookFormComponent },
    { path: "myBorrowedBooks", component: MyBorrowBooksComponent },
    { path: "fine", component: FineComponent },
    { path: "logout", component: LogoutComponent },
    { path: 'users', component: UserComponent },
    { path: 'userDetails', component: UserDetailsComponent },
    { path: 'updateUser', component: SignupComponent },
    { path: 'studentBorrowHistory', component: StudentBorrowHistoryComponent },
    { path: 'studentBooks', component: AllBooksBorrowedComponent }
];
